### Objective:
Create a python code that performs the A=CR decomposition of any matrix. You may only use the numpy package in your code.

In [1]:
import numpy as np

In [41]:
def strang_decomposition(A):
    '''
    This function performs Strang Decomposition using Gaussian Elimination given matrix A.
    '''
    gauss = np.copy(A)
    row, col = np.shape(gauss)
    j = 0 # Initialize 1st column 

    for i in range(row):
        
        # Exclude row i from further processing if all its elements are zero.
        if not np.any(gauss[i,:]):
            continue
        
        # While pivot element is 0 and the rows below pivot element only has zero values, move column j to the right.
        while np.all(gauss[i + 1:,j] == 0) and gauss[i,j] == 0 and j < col-1:
            j += 1
        
        # Identify the row below pivot element that has the largest value.
        index_max = np.argmax(gauss[i:, j]) + i
        # Swap rows to ensure that pivot element has the largest value.  
        gauss[[i, index_max]] = gauss[[index_max, i]]
        print(gauss)
        
        # Perform row-wise division by its pivot element (i,j). This transforms pivot element to 1.
        # (pivot row i) = (pivot row i) / (pivot element i,j) -> (pivot element i,j) = 1
        gauss[i, :] /= gauss[i,j] 
        print(gauss)
        
        # Transform element (k,j) below the pivot element to 0. Each element (k,j) is at row k.
        # row k = row k - (element k,j) * (pivot row i) -> (element k,j) = 0
        for k in range(i+1, row): 
            gauss[k, :] -= gauss[k,j]*gauss[i,:]
            print(gauss)
    
        # Transform element (k,j) above the pivot element to 0. Each element (k,j) is at row k.
        # row k = row k - (element k,j) * (pivot row i) -> (element k,j) = 0
        for k in range(i):
            gauss[k, :] -= gauss[k,j]*gauss[i,:]
            print(gauss)
            
    # Exclude rows that consists entirely of 0 values to obtain R matrix.
    R = gauss[~np.all(gauss == 0, axis=1)]
    # Locate the position of the first occurrence of 1 in each row of the R matrix.
    index = np.argmax(R == 1, axis=1)
    # Extract the columns corresponding to those indices to obtain C matrix.
    C = A[:, index]
    
    return gauss, C, R

In [42]:
def show_matrix(A):
    '''
    This function shows and checks the result of the Strang Decomposition function.
    '''
    G, C, R = strang_decomposition(A)
    # Multiply Matrix C and Matrix R.
    matmul = np.matmul(C,R)
    # Determine whether A = CR when the elements are rounded to 5 decimal places.
    check = np.array_equal(np.matrix.round(A, decimals = 5), np.matrix.round(matmul, decimals=5))

    print('Is A = CR? {}\n'.format(check))
    print('Matrix A:\n{}\n\nGaussian Elimination Matrix:\n{}\n\nMatrix C:\n{}\n\nMatrix R:\n{}\n'.format(A, G, C, R))
    print('Matrix Multiplication of C and R:\n{}'.format(matmul))

**Example 1:** Matrix Exercise

In [4]:
A1 = np.array([[ 1,  2,  3,  0],
               [ 1, -1,  0, -3],
               [-1,  1,  0,  3]], float)
show_matrix(A1)

Is A = CR? True

Matrix A:
[[ 1.  2.  3.  0.]
 [ 1. -1.  0. -3.]
 [-1.  1.  0.  3.]]

Gaussian Elimination Matrix:
[[ 1.  0.  1. -2.]
 [ 0.  1.  1.  1.]
 [ 0.  0.  0.  0.]]

Matrix C:
[[ 1.  2.]
 [ 1. -1.]
 [-1.  1.]]

Matrix R:
[[ 1.  0.  1. -2.]
 [ 0.  1.  1.  1.]]

Matrix Multiplication of C and R:
[[ 1.  2.  3.  0.]
 [ 1. -1.  0. -3.]
 [-1.  1.  0.  3.]]


**Example 2:** Matrix with zero as a pivot element

In [43]:
A2 = np.array([[ 1,  3,  5, 1,  0,  2],
               [ 2,  6,  4, 2,  0,  1],
               [ 4, 12,  1, 4,  0,  1]], float)
show_matrix(A2)

[[ 4. 12.  1.  4.  0.  1.]
 [ 2.  6.  4.  2.  0.  1.]
 [ 1.  3.  5.  1.  0.  2.]]
[[1.   3.   0.25 1.   0.   0.25]
 [2.   6.   4.   2.   0.   1.  ]
 [1.   3.   5.   1.   0.   2.  ]]
[[1.   3.   0.25 1.   0.   0.25]
 [0.   0.   3.5  0.   0.   0.5 ]
 [1.   3.   5.   1.   0.   2.  ]]
[[1.   3.   0.25 1.   0.   0.25]
 [0.   0.   3.5  0.   0.   0.5 ]
 [0.   0.   4.75 0.   0.   1.75]]
[[1.   3.   0.25 1.   0.   0.25]
 [0.   0.   4.75 0.   0.   1.75]
 [0.   0.   3.5  0.   0.   0.5 ]]
[[1.         3.         0.25       1.         0.         0.25      ]
 [0.         0.         1.         0.         0.         0.36842105]
 [0.         0.         3.5        0.         0.         0.5       ]]
[[ 1.          3.          0.25        1.          0.          0.25      ]
 [ 0.          0.          1.          0.          0.          0.36842105]
 [ 0.          0.          0.          0.          0.         -0.78947368]]
[[ 1.          3.          0.          1.          0.          0.15789474]
 [ 0.    

**Example 3:** Matrix with 0 value at 1st column and 1st row

In [35]:
A3 = np.array([[ 1,  0,  4,  0],
               [ 2, -2,  1, 0],
               [ 2, -1,  1, 1],
               [ 5,  2,  0, 4]], float)
show_matrix(A3)

Is A = CR? True

Matrix A:
[[ 1.  0.  4.  0.]
 [ 2. -2.  1.  0.]
 [ 2. -1.  1.  1.]
 [ 5.  2.  0.  4.]]

Gaussian Elimination Matrix:
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [-0. -0.  1.  0.]
 [-0. -0. -0.  1.]]

Matrix C:
[[ 1.  0.  4.  0.]
 [ 2. -2.  1.  0.]
 [ 2. -1.  1.  1.]
 [ 5.  2.  0.  4.]]

Matrix R:
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [-0. -0.  1.  0.]
 [-0. -0. -0.  1.]]

Matrix Multiplication of C and R:
[[ 1.  0.  4.  0.]
 [ 2. -2.  1.  0.]
 [ 2. -1.  1.  1.]
 [ 5.  2.  0.  4.]]


### **Exercise 4:** Matrix with Random Integers (0,20) and 100x500 dimension

In [7]:
Ax = np.random.randint(0, 20, (1000, 5000))
Ax = Ax.astype(float)
show_matrix(Ax)

Is A = CR? True

Matrix A:
[[12.  7. 18. ... 18. 17.  4.]
 [ 3.  4. 14. ... 10.  8. 13.]
 [14.  1.  7. ... 18. 17.  9.]
 ...
 [ 0. 17. 14. ... 13.  3. 18.]
 [ 5. 19.  8. ...  0. 10. 18.]
 [10. 17.  1. ... 19. 16. 17.]]

Gaussian Elimination Matrix:
[[  1.           0.           0.         ...  -1.43140961   6.64178358
   -4.58757788]
 [  0.           1.           0.         ...   3.65927071  -7.81485807
    5.47035796]
 [  0.           0.           1.         ...  -2.64807503   6.41989033
   -3.61698247]
 ...
 [  0.           0.           0.         ...   4.2890844   -6.7960423
    6.09524797]
 [  0.           0.           0.         ...   9.26946807 -15.68940374
   14.1760112 ]
 [  0.           0.           0.         ...   0.80683685   0.61967033
   -1.11341938]]

Matrix C:
[[12.  7. 18. ... 15. 17. 12.]
 [ 3.  4. 14. ...  9.  9.  8.]
 [14.  1.  7. ...  9. 18. 17.]
 ...
 [ 0. 17. 14. ...  8.  4. 13.]
 [ 5. 19.  8. ...  7. 11. 11.]
 [10. 17.  1. ... 16. 15.  4.]]

Matrix R:
[[  1.    