### Objective:
Create a new code or modify your Gaussian Elimination code to get PA=LU. If the matrix is a square, also calculate the determinant. Use python with only the numpy library.

In [3]:
import numpy as np

In [4]:
def LU_decomposition(A):
    '''
    This function performs LU Decomposition using Gaussian Elimination given matrix A.
    '''
    U = np.copy(A) # Copies Matrix A for U Matrix
    row, col = np.shape(U)
    P = np.diag(np.ones(row)) # Creates a matrix with diagonal 1s for P Matrix
    L = np.zeros([row, row], dtype=float) # Creates a matrix with 0s for L Matrix
    pivot_col = 0 # Initialize 1st column of Matrix U
    L_col = 0 # Initialize 1st column of Matrix L
    swap = 0 # Initialize number of swaps

    for pivot_row in range(row):
        
        # Exclude pivot_row from further processing if all its elements are zero.
        if not np.any(U[pivot_row, :]):
            continue


        
        # Identify row with the largest value
        max_row = np.argmax(abs(U[pivot_row:, pivot_col])) + pivot_row
        
        # Swap rows to ensure that pivot element has the largest value.
        if pivot_row != max_row:
            U[[pivot_row, max_row]] = U[[max_row, pivot_row]]
            P[[pivot_row, max_row]] = P[[max_row, pivot_row]]
            L[[pivot_row, max_row]] = L[[max_row, pivot_row]]
            swap += 1

        print(f'P:{P}')
        print(f'U:{U}')
        print(f'L:{L}')
        
        # Transform minus element [minus_row, pivot_col] below the pivot element [pivot_row, pivot_col] to 0.
        # constant = (minus element)/(pivot element)
        # minus_row = minus_row - constant * (pivot_row) -> minus element = 0
        for minus_row in range(pivot_row + 1, row):
            const = U[minus_row, pivot_col]/U[pivot_row, pivot_col]
            U[minus_row, :] -= const*U[pivot_row, :]
            L[minus_row, L_col] = const
            print(f'U:{U}')
            print(f'L:{L}')

        pivot_col += 1
        L_col += 1
    
    # Transforms the diagonals of Matrix L to 1.
    np.fill_diagonal(L, 1)
    # Gets the inverse of Matrix P.
    P_inv = np.linalg.inv(P)

    print(f'L:{L}')
    
    # Determinant Calculation
    if row == col:
        if swap == 0: det_P = 1
        else: det_P = (-1)**swap
        det_U = np.prod(np.diag(U))
        det_L = 1
        det_A = det_P*det_U*det_L
    else:
        det_A = None
    
    return P, U, L, P_inv, det_A

In [5]:
def show_matrix(A):
    '''
    This function shows and checks the result of the LU Decomposition function.
    '''
    P, U, L, P_inv, det_A = LU_decomposition(A)
    row, col = np.shape(A)
    
    PA = np.matrix.round(np.matmul(P,A), decimals = 2) # Multiply Matrix P and Matrix A. Round to 2 decimal places.
    LU = np.matrix.round(np.matmul(L,U), decimals = 2) # Multiply Matrix L and Matrix U. Round to 2 decimal places.
    PinvLU = np.matrix.round(np.matmul(np.matmul(P_inv, L), U), decimals = 0) # Multiply Inverse Matrix of P, Matrix L and Matrix U. Round to 2 decimal places.
    Around = np.matrix.round(A, decimals = 0) # Round to no decimal places.
    
    check_eq = np.array_equal(PA, LU) # Determine whether PA = LU.
    check_A = np.array_equal(Around, PinvLU) # Determine whether A = inverse(P)LU.
    
    print('Is PA = LU? {}'.format(check_eq))
    print('Is A = P\u207B\u00B9LU? {}\n'.format(check_A))
    
    if row == col:
        det_np = np.linalg.det(A)
        if abs(det_A) < 100000 or abs(det_np) < 100000:
            det_A_np = round(det_np)
            det_A_rd = round(det_A)
        else:
            det_A_np = np.format_float_positional(det_np, precision=5, unique=False, fractional=False, trim='-') # Calculate determinant of A using np.linalg. Set to 5 significant figures.
            det_A_rd = np.format_float_positional(det_A, precision=5, unique=False, fractional=False, trim='-') # Set to 5 significant figures.
            # Reference: https://numpy.org/devdocs/reference/generated/numpy.format_float_positional.html
        
        check_det = (det_A_rd == det_A_np) # Determine if extracted determinant = determinant solved with numpy.
        
        print('Is the calculated determinant correct? {}'.format(check_det))
        print('Extracted Determinant of Matrix A: {}'.format(det_A_rd))
        print('Numpy Determinant of Matrix A: {}\n'.format(det_A_np))
        
    print('Matrix P:\n{}\n\nMatrix A:\n{}\n\nMatrix L:\n{}\n\nMatrix U:\n{}'
          .format(np.matrix.round(P, decimals = 2), np.matrix.round(A, decimals = 2), 
                  np.matrix.round(L, decimals = 2), np.matrix.round(U, decimals = 2)))

    #Check the difference, instead of equal is close
    #RMSE

**Example 1:** Matrix Exercise

In [6]:
A1 = np.array([[ 1,  2,  3,  0],
               [ 1, -1,  0, -3],
               [-1,  1,  0,  3]], float)
show_matrix(A1)

P:[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
U:[[ 1.  2.  3.  0.]
 [ 1. -1.  0. -3.]
 [-1.  1.  0.  3.]]
L:[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
U:[[ 1.  2.  3.  0.]
 [ 0. -3. -3. -3.]
 [-1.  1.  0.  3.]]
L:[[0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]]
U:[[ 1.  2.  3.  0.]
 [ 0. -3. -3. -3.]
 [ 0.  3.  3.  3.]]
L:[[ 0.  0.  0.]
 [ 1.  0.  0.]
 [-1.  0.  0.]]
P:[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
U:[[ 1.  2.  3.  0.]
 [ 0. -3. -3. -3.]
 [ 0.  3.  3.  3.]]
L:[[ 0.  0.  0.]
 [ 1.  0.  0.]
 [-1.  0.  0.]]
U:[[ 1.  2.  3.  0.]
 [ 0. -3. -3. -3.]
 [ 0.  0.  0.  0.]]
L:[[ 0.  0.  0.]
 [ 1.  0.  0.]
 [-1. -1.  0.]]
L:[[ 1.  0.  0.]
 [ 1.  1.  0.]
 [-1. -1.  1.]]
Is PA = LU? True
Is A = P⁻¹LU? True

Matrix P:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Matrix A:
[[ 1.  2.  3.  0.]
 [ 1. -1.  0. -3.]
 [-1.  1.  0.  3.]]

Matrix L:
[[ 1.  0.  0.]
 [ 1.  1.  0.]
 [-1. -1.  1.]]

Matrix U:
[[ 1.  2.  3.  0.]
 [ 0. -3. -3. -3.]
 [ 0.  0.  0.  0.]]


**Example 2:** Matrix with zero as a pivot element

In [7]:
A2 = np.array([[ 1,  3,  5, 15,  0,  2],
               [ 2,  6,  4, 24,  0,  1],
               [ 4, 12,  1, 41,  0,  1]], float)
show_matrix(A2)

P:[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
U:[[ 4. 12.  1. 41.  0.  1.]
 [ 2.  6.  4. 24.  0.  1.]
 [ 1.  3.  5. 15.  0.  2.]]
L:[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
U:[[ 4.  12.   1.  41.   0.   1. ]
 [ 0.   0.   3.5  3.5  0.   0.5]
 [ 1.   3.   5.  15.   0.   2. ]]
L:[[0.  0.  0. ]
 [0.5 0.  0. ]
 [0.  0.  0. ]]
U:[[ 4.   12.    1.   41.    0.    1.  ]
 [ 0.    0.    3.5   3.5   0.    0.5 ]
 [ 0.    0.    4.75  4.75  0.    1.75]]
L:[[0.   0.   0.  ]
 [0.5  0.   0.  ]
 [0.25 0.   0.  ]]
P:[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
U:[[ 4.   12.    1.   41.    0.    1.  ]
 [ 0.    0.    3.5   3.5   0.    0.5 ]
 [ 0.    0.    4.75  4.75  0.    1.75]]
L:[[0.   0.   0.  ]
 [0.5  0.   0.  ]
 [0.25 0.   0.  ]]
U:[[ 4.  12.   1.  41.   0.   1. ]
 [ 0.   0.   3.5  3.5  0.   0.5]
 [ nan  nan  nan  nan  nan  nan]]
L:[[0.   0.   0.  ]
 [0.5  0.   0.  ]
 [0.25  nan 0.  ]]
P:[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
U:[[ 4.  12.   1.  41.   0.   1. ]
 [ 0.   0.   3.5  3.5  0.   0.5]
 [ nan  nan  nan  nan  nan  n

C:\Users\maryn\AppData\Local\Temp\ipykernel_24436\718834012.py:39: RuntimeWarning: invalid value encountered in double_scalars
  const = U[minus_row, pivot_col]/U[pivot_row, pivot_col]


**Example 3:** Matrix with 0 value at 1st column and 1st row

In [6]:
A3 = np.array([[ 0, -1,  6,  1],
               [ 3,  2,-12, -1],
               [ 4, -2, 12,  5],
               [ 2,  0,  0,  3]], float)
show_matrix(A3)

Is PA = LU? True
Is A = P⁻¹LU? True

Is the calculated determinant correct? True
Extracted Determinant of Matrix A: 0
Numpy Determinant of Matrix A: 0

Matrix P:
[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]

Matrix A:
[[  0.  -1.   6.   1.]
 [  3.   2. -12.  -1.]
 [  4.  -2.  12.   5.]
 [  2.   0.   0.   3.]]

Matrix L:
[[ 1.    0.    0.    0.  ]
 [ 0.75  1.    0.    0.  ]
 [ 0.5   0.29  1.    0.  ]
 [ 0.   -0.29 -0.19  1.  ]]

Matrix U:
[[  4.    -2.    12.     5.  ]
 [  0.     3.5  -21.    -4.75]
 [  0.     0.     0.     1.86]
 [  0.     0.     0.     0.  ]]


**Example 4:** Random 100x100 matrix with equal numbers of rows and columns

In [7]:
# Ax = np.random.randint(0, 20, (100, 100))
# Ax = Ax.astype(float)
Ax = np.random.randn(100,100)
show_matrix(Ax)

Is PA = LU? True
Is A = P⁻¹LU? True

Is the calculated determinant correct? True
Extracted Determinant of Matrix A: 134010000000000000000000000000000000000000000000000000000000000000000000000000
Numpy Determinant of Matrix A: 134010000000000000000000000000000000000000000000000000000000000000000000000000

Matrix P:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

Matrix A:
[[-0.13 -0.31  0.05 ... -0.09 -0.17  0.37]
 [ 1.28  0.13 -0.6  ... -0.19  1.35 -1.44]
 [-0.35 -0.69 -0.26 ... -0.96 -1.15 -0.54]
 ...
 [ 0.14 -1.82 -0.88 ... -0.17  0.47 -0.15]
 [-0.94 -0.65 -0.9  ... -0.96  0.74  0.34]
 [-0.55  0.67  0.24 ... -0.95  0.03  1.94]]

Matrix L:
[[ 1.    0.    0.   ...  0.    0.    0.  ]
 [-0.15  1.    0.   ...  0.    0.    0.  ]
 [-0.77 -0.42  1.   ...  0.    0.    0.  ]
 ...
 [-0.35 -0.14  0.19 ...  1.    0.    0.  ]
 [ 0.3   0.09 -0.13 ...  0.73  1.    0.  ]
 [ 0.24 -0.48  0.01 ..

**Example 5:** Random 500x1000 matrix with unequal numbers of rows and columns

In [8]:
# Ax = np.random.randint(0, 20, (500, 1000))
# Ax = Ax.astype(float)
Ax = np.random.randn(500,1000)
show_matrix(Ax)

Is PA = LU? True
Is A = P⁻¹LU? True

Matrix P:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

Matrix A:
[[ 0.39  0.53  0.38 ...  0.38 -0.16 -2.47]
 [-1.11  0.26 -0.45 ... -0.13  0.94 -1.48]
 [-1.26  1.43 -1.   ... -2.29 -1.1  -0.95]
 ...
 [-0.7  -0.85 -0.89 ...  1.78  0.2   0.78]
 [-1.44  0.24 -1.88 ...  0.15  0.83 -1.31]
 [ 0.36  0.99  0.61 ... -0.48 -0.78 -1.67]]

Matrix L:
[[ 1.    0.    0.   ...  0.    0.    0.  ]
 [-0.16  1.    0.   ...  0.    0.    0.  ]
 [ 0.7  -0.62  1.   ...  0.    0.    0.  ]
 ...
 [-0.65 -0.06 -0.01 ...  1.    0.    0.  ]
 [ 0.27 -0.17  0.13 ...  0.94  1.    0.  ]
 [ 0.18 -0.28 -0.14 ... -0.36  0.75  1.  ]]

Matrix U:
[[ -2.79   0.74   0.22 ...   0.53  -0.34  -0.46]
 [  0.     3.    -0.92 ...  -0.93   1.68   0.17]
 [  0.     0.    -2.68 ...   0.36   1.75  -0.27]
 ...
 [ -0.    -0.    -0.   ...  24.72   4.52   4.34]
 [  0.     0.     0.   ... -30.43  

**Example 6:** For loop for checking if resulting float matrices and determinants are correct for 1000 30x30 matrices

In [9]:
det_correct = 0
eq_correct = 0
A_correct = 0

iteration = 1000
dimension = 30

for i in range(iteration):
    # A = np.random.randint(0, 20, (dimension, dimension))
    # A = A.astype(float)
    A = np.random.randn(dimension,dimension)

    P, U, L, P_inv, det_A = LU_decomposition(A)
    row, col = np.shape(A)
    PA = np.matrix.round(np.matmul(P,A), decimals = 2) # Multiply Matrix P and Matrix A. Round to 2 decimal places.
    LU = np.matrix.round(np.matmul(L,U), decimals = 2) # Multiply Matrix L and Matrix U. Round to 2 decimal places.
    PinvLU = np.matrix.round(np.matmul(np.matmul(P_inv, L), U), decimals = 0) # Multiply Inverse Matrix of P, Matrix L and Matrix U. Round to 2 decimal places.
    Around = np.matrix.round(A, decimals = 0) # Round to no decimal places.
    
    det_np = np.linalg.det(A)
    if abs(det_A) < 100000 and abs(det_np) < 100000:
        det_A_np = round(det_np)
        det_A_rd = round(det_A)
    else:
        det_A_np = np.format_float_positional(det_np, precision=3, unique=False, fractional=False, trim='k') # Calculate determinant of A using np.linalg. Set to 5 significant figures.
        det_A_rd = np.format_float_positional(det_A, precision=3, unique=False, fractional=False, trim='k') # Set to 5 significant figures.
        # Reference: https://numpy.org/devdocs/reference/generated/numpy.format_float_positional.html
        
    check_det = (det_A_rd == det_A_np) # Determine if extracted determinant = determinant solved with numpy.
    check_eq = np.array_equal(PA, LU) # Determine whether PA = LU.
    check_A = np.array_equal(Around, PinvLU) # Determine whether A = inverse(P)LU.
    
    det_correct += 1 if check_det else 0
    eq_correct += 1 if check_eq else 0
    A_correct += 1 if check_A else 0

print('For a {}x{} matrix:'.format(dimension,dimension))
print('{} out of {} iterations have correct determinants.'.format(det_correct, iteration, dimension, dimension))
print('{} out of {} iterations are PA = CR.'.format(eq_correct, iteration, dimension, dimension))
print('{} out of {} iterations are A = P\u207B\u00B9LU.'.format(A_correct, iteration, dimension, dimension))

For a 30x30 matrix:
1000 out of 1000 iterations have correct determinants.
1000 out of 1000 iterations are PA = CR.
1000 out of 1000 iterations are A = P⁻¹LU.
