### Objective:
Create a code that calculates for a Hessenberg matrix that is similar to an input matrix A using householder reflections.

Reference for verifying answers:
https://www.wolframalpha.com/input?i=hessenberg+decomposition&assumption=%7B%22F%22%2C+%22HessenbergDecompositionCalculator%22%2C+%22theMatrix%22%7D+-%3E%22%7B%7B5%2C4%2C7%2C2%2C5%7D%2C%7B5%2C3%2C-1%2C2%2C6%7D%2C%7B-3%2C5%2C2%2C3%2C-3%7D%2C%7B3%2C2%2C1%2C4%2C-2%7D%2C+%7B1%2C3%2C-2%2C3%2C-4%7D%7D%22&assumption=%7B%22C%22%2C+%22hessenberg+decomposition%22%7D+-%3E+%7B%22Calculator%22%2C+%22dflt%22%7D

In [3]:
import numpy as np

In [4]:
def hessenberg(A):
    ref = np.copy(A)
    row, col = np.shape(ref)
    
    if row != col:
        raise ValueError('Matrix A is not a square matrix.')
    
    for i in range(row-2):
        x = ref[i+1:, i, None]
        w = np.zeros_like(x)
        w[0] = np.linalg.norm(x)*np.sign(x[0])
        v = x + w
        P = (v@v.T)/(v.T@v)[0]
        H = np.identity(row)
        H[i+1:,i+1:] -= 2*P 
        ref  = H@ref@H
    H_round = np.matrix.round(ref,3)
    print(f'Eigvalues of H: \n{np.linalg.eigvals(ref)}')
    print(f'Eigvalues of A: \n{np.linalg.eigvals(A)}')
    print(f'Hessenberg Matrix: \n{H_round}\n')

In [26]:
def hessenberg_(matrix):
    H = np.copy(matrix)
    row, col = np.shape(A)
    M = np.eye(row)
    Minv = np.eye(row)
    
    if row != col:
        raise ValueError('Matrix A is not a square matrix.')
    
    for i in range(row-2):
        x = H[i+1:, i, None]
        w = np.zeros_like(x)
        w[0] = - np.linalg.norm(x) * np.sign(x[0])
        print(f'w:{w}')
        u = w - x
        print(f'u:{u}')
        v = u / np.linalg.norm(u)
        print(f'v:{v}')
        P = np.eye(row)
        P[i+1:,i+1:] = np.eye(len(x)) - 2 * np.outer(v,v)
        print(f'P:{P}')
        H = P @ H @ P.T
        M = P @ M
        Minv = P @ Minv
        print(f'H:{H}')
        print(f'M:{M}')

    H = np.matrix.round(H,3)
    print(f'Eigvalues of A: \n{np.linalg.eigvals(matrix)}')
    print(f'Eigvalues of H: \n{np.linalg.eigvals(H)}')
    print(f'Hessenberg Matrix: \n{H}\n')

In [31]:
A = np.array([[1, 1, 3, 1],
              [1, 2, 0, 1],
              [2, 3, 0, 1],
              [0, 0, 1, 2]],float)
#hessenberg(A)
hessenberg_(A)


w:[[-2.23606798]
 [ 0.        ]
 [ 0.        ]]
u:[[-3.23606798]
 [-2.        ]
 [ 0.        ]]
v:[[-0.85065081]
 [-0.52573111]
 [ 0.        ]]
P:[[ 1.          0.          0.          0.        ]
 [ 0.         -0.4472136  -0.89442719  0.        ]
 [ 0.         -0.89442719  0.4472136   0.        ]
 [ 0.          0.          0.          1.        ]]
H:[[ 1.         -3.13049517  0.4472136   1.        ]
 [-2.23606798  1.6         3.2        -1.34164079]
 [ 0.          0.2         0.4        -0.4472136 ]
 [ 0.         -0.89442719  0.4472136   2.        ]]
M:[[ 1.          0.          0.          0.        ]
 [ 0.         -0.4472136  -0.89442719  0.        ]
 [ 0.         -0.89442719  0.4472136   0.        ]
 [ 0.          0.          0.          1.        ]]
w:[[-0.91651514]
 [ 0.        ]]
u:[[-1.11651514]
 [ 0.89442719]]
v:[[-0.78045432]
 [ 0.62521281]]
P:[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.         -0.218

In [28]:
A = np.array([[ 5, 4, 7, 2, 5],
              [ 5, 3,-1, 2, 6],
              [-3, 5, 2, 3,-3],
              [ 3, 2, 1, 4,-2],
              [ 1, 3,-2, 3,-4]], float)
hessenberg(A)
hessenberg_(A)


Eigvalues of H: 
[12.13382055+0.j         -5.05449196+0.j          0.46249122+4.85736868j
  0.46249122-4.85736868j  1.99568898+0.j        ]
Eigvalues of A: 
[12.13382055+0.j         -5.05449196+0.j          0.46249122+4.85736868j
  0.46249122-4.85736868j  1.99568898+0.j        ]
Hessenberg Matrix: 
[[ 5.    -1.508 -9.575  0.146  0.128]
 [-6.633  3.455  1.772  3.691  0.59 ]
 [-0.     6.683  1.503 -5.285  2.207]
 [ 0.     0.    -4.046 -2.806  1.415]
 [ 0.     0.     0.    -4.109  2.848]]

w:[[-6.63324958]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
u:[[-11.63324958]
 [  3.        ]
 [ -3.        ]
 [ -1.        ]]
v:[[-0.93642361]
 [ 0.24148634]
 [-0.24148634]
 [-0.08049545]]
P:[[ 1.          0.          0.          0.          0.        ]
 [ 0.         -0.75377836  0.45226702 -0.45226702 -0.15075567]
 [ 0.          0.45226702  0.8833687   0.1166313   0.0388771 ]
 [ 0.         -0.45226702  0.1166313   0.8833687  -0.0388771 ]
 [ 0.         -0.15075567  0.0388771  -0.0388771   0.98704097

In [29]:
A = np.array([[1,1,0],
              [0,2,1],
              [1,2,0]],float)
P = np.array([[1,2,2],
              [0,1,0],
              [1,0,1]], float)

print(A@P@A.T)

[[ 4.  8.  7.]
 [ 3.  5.  5.]
 [ 5. 10.  9.]]
