### Objective:
Create a code that calculates all the eigenvalues of a matrix A using the QR algorithm. If the matrix A is symmetric, then include all the eigenvectors. 

In [86]:
import numpy as np

def QR(matrix, iterations = 10):
    
    A = np.copy(matrix)
    row, col = np.shape(A)
    if row != col: raise ValueError('Matrix A is not a square matrix.')
        
    # Hessenberg Matrix
    for i in range(row-2):    
        x = A[i+1:, i, None]
        w = np.zeros_like(x)
        w[0] = np.linalg.norm(x) * np.sign(x[0])
        v = x + w
        P = (v @ v.T) / (v.T @ v)[0]
        H = np.eye(row)
        H[i+1:,i+1:] -= 2*P 
        A  = H @ A @ H
    print(f'Hessenberg Matrix:\n{np.round(A,0)}')
    
    # Schur Matrix
    Q = np.eye(row)
    S = np.copy(A)
    eigenvalues = np.zeros((row,))
    iterate = 0
    while iterate < iterations:
        
        # Wilkinson Shift
        a, b, d, c = S[row-2:row, row-2:row].flatten()
        l = (a-c)/2
        sgn = -1 if l >= 0 else 1
        k = c + sgn * (b**2) / (l + np.sqrt(l**2 + b**2))
        S = S - np.eye(row) * k
        
        # Givens Rotation
        QT = np.eye(row)
        for i in range(row-2,-1,-1):
            if np.abs(S[i+1, i]) < 1e-10: continue
            a, b = S[i, i], S[i+1, i]
            r = np.hypot(a, b)
            cos = a / r
            sin = b / r 
            G = np.eye(row)
            G[i,i], G[i+1,i+1], G[i,i+1], G[i+1,i] = cos, cos, sin, -sin
            QT = G @ QT
                
        R = QT @ A
        Q = QT.T
        S = R @ Q
        S = S + np.eye(row) * k
        S[abs(S) < 1e-10] = 0
        iterate += 1
        
    print(f'Schur Matrix:\n{np.round(S,0)}')
    print(f'Eigenvalues:\n{np.diagonal(S)}')     
    
A = np.array([[ 3, 7,-8,-2,10, 6],
              [ 3,-7,-2, 4,-7, 3],
              [-7,-8,-1,-7,-1,-7],
              [-7,-1,-9,-9,-3, 9],
              [-8, 4, 7, 4,-5,-10],
              [ 2, 0, 9, 6, 8, 8]], float)

QR(A) # Was not able to make it run correctly :(

Hessenberg Matrix:
[[  3.  -2.  -7.   5. -12.   5.]
 [-13.  -7.   2.   6.   7.  -1.]
 [ -0. -16.  -5.  -1.   2.   9.]
 [  0.   0.  15.   2.   4.  -3.]
 [ -0.   0.  -0.  10.   1.  -0.]
 [ -0.  -0.  -0.   0. -11.  -5.]]
Schur Matrix:
[[-76.   7.  -4.   3. -10.  -3.]
 [ -6. -80.  -5.   7.  -5.  -7.]
 [ -2. -17. -79.  -4.  -3.   9.]
 [ -2.   3.  17. -85.   2.  -5.]
 [ -1.   2.  -2.  11. -83.   4.]
 [  2.  -2.   2.   1.  -7. -87.]]
Eigenvalues:
[-76.1798195  -79.66042776 -78.864164   -85.08933442 -82.88963699
 -86.77851804]
