### Objective:
Calculate \(U\), \(\Sigma\) and \(V^T\) of any matrix A using Golub Kahan for the tridiagonals and Golub-Reinsch for the bidiagonals. 

In [12]:
import numpy as np

In [13]:

def Householder(x, i):
    alpha = -np.copysign(np.linalg.norm(x), x[i])
    v = x.copy()
    v[i] -= alpha
    v /= np.linalg.norm(v)
    return np.eye(len(x)) - 2 * np.outer(v, v)


In [14]:
def Bidiag(X):
    J = X.copy()
    n, m = J.shape

    for i in range(m - 2):
        # column
        h = np.zeros(n)
        h[i:] = J[i:, i]
        P = Householder(h, i)
        J = P @ J
        J = np.where(np.abs(J) < 9e-15, 0, J)
        print(J, '\n')

        # row
        h = np.zeros(m)
        h[i+1:] = J[i, i+1:] 
        Q = Householder(h, i+1)
        J = J @ Q
        J = np.where(np.abs(J) < 9e-15, 0, J)
        print(J, '\n')
        
    return J

In [15]:

A = np.array([[3, 2, 1, 4, 2],
             [2, 3, 1, 0, 5], 
             [1, 2, 5, 4, 3], 
             [4, 2, 0, 2, 9]], dtype=float)

In [17]:

J = Bidiag(A)

[[ -5.47722558  -4.01663209  -1.82574186  -4.38178046 -10.04158022]
 [  0.           1.58051858   0.33333333  -1.97748199   2.15907519]
 [  0.           1.29025929   4.66666667   3.011259     1.5795376 ]
 [  0.          -0.83896284  -1.33333333  -1.95496398   3.31815038]] 

[[-5.47722558 11.81101181  0.          0.          0.        ]
 [ 0.         -1.69101322 -0.04404264 -2.88318433  0.08350733]
 [ 0.         -3.620211    4.10023674  1.65182718 -1.53582699]
 [ 0.         -1.60436066 -1.42162309 -2.1668594   2.83255671]] 

[[-5.47722558 11.81101181  0.          0.          0.        ]
 [ 0.          4.30574343 -2.9004165   0.5508837   0.20306905]
 [ 0.          0.          2.3758586   3.72495631 -1.4636482 ]
 [ 0.          0.         -2.18581182 -1.24811549  2.86454402]] 

[[-5.47722558 11.81101181  0.          0.          0.        ]
 [ 0.          4.30574343  2.95924412  0.          0.        ]
 [ 0.          0.         -1.73564033  4.11149025 -1.32116245]
 [ 0.          0.         